# Generated by Django 4.0.6 on 2022-07-17 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0011_alter_detection_detection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='detection_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 12, 14, 53, 343178)),
        ),
    ]
