# Generated by Django 4.0.6 on 2022-07-17 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0013_alter_detection_detection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='detection_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
