# Generated by Django 4.0.6 on 2022-07-13 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='detection_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
