# Generated by Django 4.0.6 on 2022-07-13 10:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_device_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='detection_date',
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_date', models.DateTimeField(default=datetime.datetime.now)),
                ('open_ports', models.JSONField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.device')),
            ],
        ),
    ]
