# Generated by Django 4.0.6 on 2022-07-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_remove_device_detection_date_detection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('PWS', 'Personal Web Server'), ('R', 'Router'), ('P', 'Printer'), ('C', 'Camera'), ('U', 'Unknown')], default='U', max_length=50),
        ),
    ]
