# Generated by Django 4.0.6 on 2022-07-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_alter_device_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.device'),
        ),
    ]
