# Generated by Django 4.0.6 on 2022-07-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_remove_device_device_type_detection_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='detected',
            field=models.BooleanField(default=False),
        ),
    ]
