# Generated by Django 4.0.6 on 2022-07-17 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0012_alter_detection_detection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='detection_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 12, 54, 33, 820632)),
        ),
        migrations.AlterField(
            model_name='detection',
            name='device_type',
            field=models.CharField(choices=[('Página web personal', 'Personal Web Server'), ('Router', 'Router'), ('Impresora', 'Printer'), ('Cámara', 'Camera'), ('Desconocido', 'Unknown')], default='Desconocido', max_length=50),
        ),
    ]
