# Generated by Django 4.1.1 on 2022-09-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='format',
            field=models.CharField(choices=[('Dirección IP', 'Ip'), ('Dirección URL', 'Url'), ('Rango de red', 'Rango')], default='Dirección IP', max_length=20),
        ),
    ]
