# Generated by Django 4.0.6 on 2022-09-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='format',
            field=models.CharField(choices=[('Dirección IP', 'Ip'), ('Dirección URL', 'Url'), ('Rango', 'Rango')], default='Dirección IP', max_length=20),
        ),
    ]
